#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Jun 10, 2022 02:01:53 PM +0700  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import form.gui_support


class Toplevel1:
    def __init__(self, top=None):
        """This class configures and populates the toplevel window.
        top is the toplevel containing window."""
        _bgcolor = "#E9EBEE"  # Closest X11 color: 'gray92'
        _fgcolor = "#000000"  # X11 color: 'black'
        _compcolor = "#E9EBEE"  # Closest X11 color: 'gray92'
        _ana1color = "#E9EBEE"  # Closest X11 color: 'gray92'
        _ana2color = "#ececec"  # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use("winnative")
        self.style.configure(".", background=_bgcolor)
        self.style.configure(".", foreground=_fgcolor)
        self.style.configure(".", font="TkDefaultFont")
        self.style.map(".", background=[("selected", _compcolor), ("active", _ana2color)])

        top.geometry("835x399+243+178")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("Gmaill Changer")
        top.configure(background="#E9EBEE")
        top.configure(highlightbackground="#E9EBEE")
        top.configure(highlightcolor="black")

        self.top = top
        self.combobox = tk.StringVar()
        self.checkCheckLinkYoutube = tk.IntVar()
        self.checkCheckDate = tk.IntVar()
        self.checkChangePass = tk.IntVar()
        self.checkChangeEmailRecovery = tk.IntVar()
        self.checkDeletePhoneRecovery = tk.IntVar()
        self.checkPause = tk.IntVar()
        self.checkRestoreDisable = tk.IntVar()
        self.checkRestoreDisableNoLogin = tk.IntVar()
        self.checkEmailGmailCom = tk.IntVar()
        self.checkChangeLanguageEN = tk.IntVar()
        self.checkCheckGoogleAdw = tk.IntVar()
        self.checkCheckPhoneRecovery = tk.IntVar()
        self.checkCheckCountry = tk.IntVar()
        self.checkCHPlay = tk.IntVar()
        self.checkGoogleAdsense = tk.IntVar()
        self.checkGoogleVoice = tk.IntVar()
        self.checkDeviceLogout = tk.IntVar()
        self.checkPaymentMethods = tk.IntVar()
        self.checkClosePaymentMethods = tk.IntVar()
        self.checkDeletePaymentMethods = tk.IntVar()
        self.checkCreateChannelYoutube = tk.IntVar()
        self.checkConfirmSecurityActivity = tk.IntVar()
        self.checkCheckLiveDie = tk.IntVar()
        self.checkTatHinhAnh = tk.IntVar()
        self.checkVerifyphone = tk.IntVar()

        self.adad = tk.Checkbutton(self.top)
        self.adad.place(relx=0.012, rely=0.0, relheight=0.048, relwidth=0.23)
        self.adad.configure(activebackground="#ececec")
        self.adad.configure(activeforeground="red")
        self.adad.configure(anchor="w")
        self.adad.configure(background="#E9EBEE")
        self.adad.configure(compound="left")
        self.adad.configure(disabledforeground="#a3a3a3")
        self.adad.configure(foreground="#000000")
        self.adad.configure(highlightbackground="#E9EBEE")
        self.adad.configure(highlightcolor="black")
        self.adad.configure(justify="left")
        self.adad.configure(text="""Check link youtube""")
        self.adad.configure(variable=self.checkCheckLinkYoutube)
        self.tooltip_font = "TkDefaultFont"
        self.adad_tooltip = ToolTip(self.adad, self.tooltip_font, """Kiểm tra thông tin youtube""")

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.sub_menu = tk.Menu(
            top, activebackground="#ececec", activeborderwidth=1, activeforeground="red", background="#E9EBEE", borderwidth=1, disabledforeground="#a3a3a3", foreground="#000000", tearoff=0
        )
        self.menubar.add_cascade(menu=self.sub_menu, label="SETTINGS")
        self.sub_menu1 = tk.Menu(
            top, activebackground="#ececec", activeborderwidth=1, activeforeground="red", background="#E9EBEE", borderwidth=1, disabledforeground="#a3a3a3", foreground="#000000", tearoff=0
        )
        self.sub_menu.add_cascade(menu=self.sub_menu1, label="RESTORE DISABLE")
        self.sub_menu1.add_command(label="content (list)")
        self.sub_menu1.add_command(label="mail (list)")
        self.sub_menu1.add_command(label="domain (list)")
        self.sub_menu.add_command(label="EMAIL RECOVERY (LIST)")
        self.sub_menu.add_command(label="API KEY CAPTCHA (1 KEY)")
        self.sub_menu12 = tk.Menu(
            top, activebackground="#ececec", activeborderwidth=1, activeforeground="red", background="#E9EBEE", borderwidth=1, disabledforeground="#a3a3a3", foreground="#000000", tearoff=0
        )
        self.sub_menu.add_cascade(menu=self.sub_menu12, label="PROXY")
        self.sub_menu12.add_command(label="CYBER GHOST (LIST COUNTRY)")
        self.sub_menu12.add_command(label="VYPR (LIST COUNTRY)")
        self.sub_menu12.add_command(label="TMPROXY (1 KEY)")
        self.sub_menu12.add_command(label="LIST PROXY (LIST IP:PORT)")
        self.sub_menu12.add_command(label="IPVANISH (LIST COUNTRY)")
        self.sub_menu12.add_command(label="EXPRESS (LIST COUNTRY)")
        self.sub_menu12.add_command(label="DCOM (NAME)")
        self.sub_menu12.add_command(label="SSH (LIST IP|USER|PASS)")
        self.sub_menu12.add_command(label="HMA NEW (LIST COUNTRY)")
        self.sub_menu12.add_command(label="911 (LIST COUNTRY)")
        self.sub_menu.add_command(label="PASSWORD (LIST)")
        self.sub_menu.add_command(label="EMAIL RECOVERY DOMAIN (1 DOMAIN)")
        self.sub_menu.add_command(label="PASSWORD KEY (1 KEY)")
        self.sub_menu.add_command(label="KEY ACTIVE")
        self.sub_menu.add_command(label="VERIFY PHONE")
        self.sub_menu.add_command(compound="left", label="USER AGENT (LIST)")
        self.sub_menu123 = tk.Menu(
            top, activebackground="#ececec", activeborderwidth=1, activeforeground="red", background="#E9EBEE", borderwidth=1, disabledforeground="#a3a3a3", foreground="#000000", tearoff=0
        )
        self.menubar.add_cascade(menu=self.sub_menu123, label="WEBMAIL")
        self.sub_menu123.add_command(label="ADD MAIL")
        self.sub_menu123.add_command(label="DELETE MAIL")
        self.sub_menu123.add_command(label="OPEN WEB MAIL")
        self.sub_menu123.add_command(label="VPS ONLINE SETUP")
        self.sub_menu123.add_command(label="LÔ MAIL")
        self.sub_menu1234 = tk.Menu(
            top, activebackground="#ececec", activeborderwidth=1, activeforeground="red", background="#E9EBEE", borderwidth=1, disabledforeground="#a3a3a3", foreground="#000000", tearoff=0
        )
        self.menubar.add_cascade(menu=self.sub_menu1234, label="HELP")
        self.sub_menu1234.add_command(label="GUIDE")
        self.sub_menu1234.add_command(label="UPDATE NEW VERSION")
        self.sub_menu1234.add_command(label="OPEN FOLDER TOOL")
        self.sub_menu1234.add_command(label="OPEN HCONFIG")

        self.adad_1 = tk.Checkbutton(self.top)
        self.adad_1.place(relx=0.012, rely=0.045, relheight=0.048, relwidth=0.183)
        self.adad_1.configure(activebackground="#ececec")
        self.adad_1.configure(activeforeground="red")
        self.adad_1.configure(anchor="w")
        self.adad_1.configure(background="#E9EBEE")
        self.adad_1.configure(compound="left")
        self.adad_1.configure(disabledforeground="#a3a3a3")
        self.adad_1.configure(foreground="#000000")
        self.adad_1.configure(highlightbackground="#E9EBEE")
        self.adad_1.configure(highlightcolor="black")
        self.adad_1.configure(justify="left")
        self.adad_1.configure(text="""Check date create""")
        self.adad_1.configure(variable=self.checkCheckDate)
        self.tooltip_font = "TkDefaultFont"
        self.adad_1_tooltip = ToolTip(self.adad_1, self.tooltip_font, """Kiểm tra ngày tạo mail""")

        self.adad_1_1 = tk.Checkbutton(self.top)
        self.adad_1_1.place(relx=0.012, rely=0.09, relheight=0.048, relwidth=0.182)
        self.adad_1_1.configure(activebackground="#ececec")
        self.adad_1_1.configure(activeforeground="red")
        self.adad_1_1.configure(anchor="w")
        self.adad_1_1.configure(background="#E9EBEE")
        self.adad_1_1.configure(compound="left")
        self.adad_1_1.configure(disabledforeground="#a3a3a3")
        self.adad_1_1.configure(foreground="#000000")
        self.adad_1_1.configure(highlightbackground="#E9EBEE")
        self.adad_1_1.configure(highlightcolor="black")
        self.adad_1_1.configure(justify="left")
        self.adad_1_1.configure(text="""Change pass""")
        self.adad_1_1.configure(variable=self.checkChangePass)
        self.tooltip_font = "TkDefaultFont"
        self.adad_1_1_tooltip = ToolTip(self.adad_1_1, self.tooltip_font, """Thay đổi mật khẩu""")

        self.adad_1_1_1 = tk.Checkbutton(self.top)
        self.adad_1_1_1.place(relx=0.012, rely=0.135, relheight=0.048, relwidth=0.181)
        self.adad_1_1_1.configure(activebackground="#ececec")
        self.adad_1_1_1.configure(activeforeground="red")
        self.adad_1_1_1.configure(anchor="w")
        self.adad_1_1_1.configure(background="#E9EBEE")
        self.adad_1_1_1.configure(compound="left")
        self.adad_1_1_1.configure(disabledforeground="#a3a3a3")
        self.adad_1_1_1.configure(foreground="#000000")
        self.adad_1_1_1.configure(highlightbackground="#E9EBEE")
        self.adad_1_1_1.configure(highlightcolor="black")
        self.adad_1_1_1.configure(justify="left")
        self.adad_1_1_1.configure(text="""Change email recovery""")
        self.adad_1_1_1.configure(variable=self.checkChangeEmailRecovery)
        self.tooltip_font = "TkDefaultFont"
        self.adad_1_1_1_tooltip = ToolTip(self.adad_1_1_1, self.tooltip_font, """Thay đổi email khôi phục""")

        self.adad_1_1_1_1 = tk.Checkbutton(self.top)
        self.adad_1_1_1_1.place(relx=0.012, rely=0.18, relheight=0.048, relwidth=0.204)
        self.adad_1_1_1_1.configure(activebackground="#ececec")
        self.adad_1_1_1_1.configure(activeforeground="red")
        self.adad_1_1_1_1.configure(anchor="w")
        self.adad_1_1_1_1.configure(background="#E9EBEE")
        self.adad_1_1_1_1.configure(compound="left")
        self.adad_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.adad_1_1_1_1.configure(foreground="#000000")
        self.adad_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.adad_1_1_1_1.configure(highlightcolor="black")
        self.adad_1_1_1_1.configure(justify="left")
        self.adad_1_1_1_1.configure(text="""Delete phone recovery""")
        self.adad_1_1_1_1.configure(variable=self.checkDeletePhoneRecovery)
        self.tooltip_font = "TkDefaultFont"
        self.adad_1_1_1_1_tooltip = ToolTip(self.adad_1_1_1_1, self.tooltip_font, """Xóa tất cả số điện thoại""")

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.686, rely=0.175, height=19, width=66)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor="w")
        self.Label1.configure(background="#E9EBEE")
        self.Label1.configure(compound="left")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#E9EBEE")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text="""Thread""")
        self.tooltip_font = "TkDefaultFont"
        self.Label1_tooltip = ToolTip(self.Label1, self.tooltip_font, """Số luồng""")

        self.spinThread = ttk.Spinbox(self.top, from_=1, to=100)
        self.spinThread.place(relx=0.746, rely=0.175, relheight=0.048, relwidth=0.103)
        self.spinThread.configure(background="white")
        self.spinThread.configure(takefocus="")

        self.txtLog = tk.Text(self.top)
        self.txtLog.place(relx=0.012, rely=0.519, relheight=0.333, relwidth=0.957)
        self.txtLog.configure(background="white")
        self.txtLog.configure(font="TkTextFont")
        self.txtLog.configure(foreground="black")
        self.txtLog.configure(highlightbackground="#E9EBEE")
        self.txtLog.configure(highlightcolor="black")
        self.txtLog.configure(insertbackground="black")
        self.txtLog.configure(selectbackground="blue")
        self.txtLog.configure(selectforeground="white")
        self.txtLog.configure(wrap="word")

        self.lbStatus = tk.Label(self.top)
        self.lbStatus.place(relx=0.012, rely=0.865, height=22, width=794)
        self.lbStatus.configure(activebackground="#f9f9f9")
        self.lbStatus.configure(activeforeground="red")
        self.lbStatus.configure(anchor="w")
        self.lbStatus.configure(background="#E9EBEE")
        self.lbStatus.configure(compound="left")
        self.lbStatus.configure(disabledforeground="#a3a3a3")
        self.lbStatus.configure(foreground="#ff0000")
        self.lbStatus.configure(highlightbackground="#E9EBEE")
        self.lbStatus.configure(highlightcolor="#000000")
        self.lbStatus.configure(text="""...""")

        self.lbHsd = tk.Label(self.top)
        self.lbHsd.place(relx=0.012, rely=0.907, height=22, width=791)
        self.lbHsd.configure(activebackground="#f9f9f9")
        self.lbHsd.configure(activeforeground="red")
        self.lbHsd.configure(anchor="w")
        self.lbHsd.configure(background="#E9EBEE")
        self.lbHsd.configure(compound="left")
        self.lbHsd.configure(disabledforeground="#a3a3a3")
        self.lbHsd.configure(foreground="#0000ff")
        self.lbHsd.configure(highlightbackground="#E9EBEE")
        self.lbHsd.configure(highlightcolor="#000000")
        self.lbHsd.configure(text="""...""")

        self.btnOpenMail = ttk.Button(self.top)
        self.btnOpenMail.place(relx=0.686, rely=0.251, height=30, width=233)
        self.btnOpenMail.configure(takefocus="")
        self.btnOpenMail.configure(text="""Open Mail""")
        self.btnOpenMail.configure(compound="left")
        self.tooltip_font = "TkDefaultFont"
        self.btnOpenMail_tooltip = ToolTip(self.btnOpenMail, self.tooltip_font, """Mở web mail""")

        self.btnRun = ttk.Button(self.top)
        self.btnRun.place(relx=0.686, rely=0.351, height=30, width=233)
        self.btnRun.configure(takefocus="")
        self.btnRun.configure(text="""Run""")
        self.btnRun.configure(compound="left")
        self.tooltip_font = "TkDefaultFont"
        self.btnRun_tooltip = ToolTip(self.btnRun, self.tooltip_font, """Chạy""")

        self.comboProxy = ttk.Combobox(self.top)
        self.comboProxy.place(relx=0.746, rely=0.025, relheight=0.048, relwidth=0.212)
        self.comboProxy.configure(textvariable=self.combobox)
        self.comboProxy.configure(takefocus="")

        self.Label1_1 = tk.Label(self.top)
        self.Label1_1.place(relx=0.686, rely=0.025, height=19, width=45)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(anchor="w")
        self.Label1_1.configure(background="#E9EBEE")
        self.Label1_1.configure(compound="left")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#E9EBEE")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text="""Proxy""")
        self.tooltip_font = "TkDefaultFont"
        self.Label1_1_tooltip = ToolTip(self.Label1_1, self.tooltip_font, """Số luồng""")

        self.adad_2 = tk.Checkbutton(self.top)
        self.adad_2.place(relx=0.89, rely=0.175, relheight=0.058, relwidth=0.075)

        self.adad_2.configure(activebackground="#ececec")
        self.adad_2.configure(activeforeground="red")
        self.adad_2.configure(anchor="w")
        self.adad_2.configure(background="#E9EBEE")
        self.adad_2.configure(compound="left")
        self.adad_2.configure(disabledforeground="#a3a3a3")
        self.adad_2.configure(foreground="#000000")
        self.adad_2.configure(highlightbackground="#E9EBEE")
        self.adad_2.configure(highlightcolor="black")
        self.adad_2.configure(justify="left")
        self.adad_2.configure(text="""Pause""")
        self.adad_2.configure(variable=self.checkPause)
        self.tooltip_font = "TkDefaultFont"
        self.adad_2_tooltip = ToolTip(self.adad_2, self.tooltip_font, """Tạm dừng""")

        self.Checkbutton1 = tk.Checkbutton(self.top)
        self.Checkbutton1.place(relx=0.251, rely=0.0, relheight=0.048, relwidth=0.145)
        self.Checkbutton1.configure(activebackground="#ececec")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(anchor="w")
        self.Checkbutton1.configure(background="#E9EBEE")
        self.Checkbutton1.configure(compound="left")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify="left")
        self.Checkbutton1.configure(text="""Restore disable""")
        self.Checkbutton1.configure(variable=self.checkRestoreDisable)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton1_tooltip = ToolTip(self.Checkbutton1, self.tooltip_font, """Kháng mail""")

        self.Checkbutton2 = tk.Checkbutton(self.top)
        self.Checkbutton2.place(relx=0.251, rely=0.045, relheight=0.048, relwidth=0.182)
        self.Checkbutton2.configure(activebackground="#ececec")
        self.Checkbutton2.configure(activeforeground="#000000")
        self.Checkbutton2.configure(anchor="w")
        self.Checkbutton2.configure(background="#E9EBEE")
        self.Checkbutton2.configure(compound="left")
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(foreground="#000000")
        self.Checkbutton2.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2.configure(highlightcolor="black")
        self.Checkbutton2.configure(justify="left")
        self.Checkbutton2.configure(text="""Restore disable web""")
        self.Checkbutton2.configure(variable=self.checkRestoreDisableNoLogin)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_tooltip = ToolTip(self.Checkbutton2, self.tooltip_font, """Kháng mail web""")

        self.adad_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.adad_1_1_1_1_1.place(relx=0.012, rely=0.226, relheight=0.048, relwidth=0.21)
        self.adad_1_1_1_1_1.configure(activebackground="#ececec")
        self.adad_1_1_1_1_1.configure(activeforeground="red")
        self.adad_1_1_1_1_1.configure(anchor="w")
        self.adad_1_1_1_1_1.configure(background="#E9EBEE")
        self.adad_1_1_1_1_1.configure(compound="left")
        self.adad_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.adad_1_1_1_1_1.configure(foreground="#000000")
        self.adad_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.adad_1_1_1_1_1.configure(highlightcolor="black")
        self.adad_1_1_1_1_1.configure(justify="left")
        self.adad_1_1_1_1_1.configure(text="""Check email @gmail.com""")
        self.adad_1_1_1_1_1.configure(variable=self.checkEmailGmailCom)

        self.Checkbutton2_1 = tk.Checkbutton(self.top)
        self.Checkbutton2_1.place(relx=0.251, rely=0.09, relheight=0.048, relwidth=0.23)
        self.Checkbutton2_1.configure(activebackground="#ececec")
        self.Checkbutton2_1.configure(activeforeground="#000000")
        self.Checkbutton2_1.configure(anchor="w")
        self.Checkbutton2_1.configure(background="#E9EBEE")
        self.Checkbutton2_1.configure(compound="left")
        self.Checkbutton2_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2_1.configure(foreground="#000000")
        self.Checkbutton2_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2_1.configure(highlightcolor="black")
        self.Checkbutton2_1.configure(justify="left")
        self.Checkbutton2_1.configure(text="""Change language en""")
        self.Checkbutton2_1.configure(variable=self.checkChangeLanguageEN)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_1_tooltip = ToolTip(self.Checkbutton2_1, self.tooltip_font, """Đổi ngôn ngữ sang tiếng anh""")

        self.Checkbutton2_1_1 = tk.Checkbutton(self.top)
        self.Checkbutton2_1_1.place(relx=0.251, rely=0.135, relheight=0.048, relwidth=0.23)
        self.Checkbutton2_1_1.configure(activebackground="#ececec")
        self.Checkbutton2_1_1.configure(activeforeground="#000000")
        self.Checkbutton2_1_1.configure(anchor="w")
        self.Checkbutton2_1_1.configure(background="#E9EBEE")
        self.Checkbutton2_1_1.configure(compound="left")
        self.Checkbutton2_1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2_1_1.configure(foreground="#000000")
        self.Checkbutton2_1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2_1_1.configure(highlightcolor="black")
        self.Checkbutton2_1_1.configure(justify="left")
        self.Checkbutton2_1_1.configure(text="""Check google adw""")
        self.Checkbutton2_1_1.configure(variable=self.checkCheckGoogleAdw)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_1_1_tooltip = ToolTip(self.Checkbutton2_1_1, self.tooltip_font, """Kiểm tra tài khoản google adw""")

        self.Checkbutton2_1_1_1 = tk.Checkbutton(self.top)
        self.Checkbutton2_1_1_1.place(relx=0.251, rely=0.18, relheight=0.048, relwidth=0.248)
        self.Checkbutton2_1_1_1.configure(activebackground="#ececec")
        self.Checkbutton2_1_1_1.configure(activeforeground="#000000")
        self.Checkbutton2_1_1_1.configure(anchor="w")
        self.Checkbutton2_1_1_1.configure(background="#E9EBEE")
        self.Checkbutton2_1_1_1.configure(compound="left")
        self.Checkbutton2_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2_1_1_1.configure(foreground="#000000")
        self.Checkbutton2_1_1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2_1_1_1.configure(highlightcolor="black")
        self.Checkbutton2_1_1_1.configure(justify="left")
        self.Checkbutton2_1_1_1.configure(text="""Check phone recovery""")
        self.Checkbutton2_1_1_1.configure(variable=self.checkCheckPhoneRecovery)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_1_1_1_tooltip = ToolTip(self.Checkbutton2_1_1_1, self.tooltip_font, """Kiểm tra số điện thoại khôi phục""")

        self.Checkbutton2_1_1_1_1 = tk.Checkbutton(self.top)
        self.Checkbutton2_1_1_1_1.place(relx=0.251, rely=0.226, relheight=0.048, relwidth=0.248)
        self.Checkbutton2_1_1_1_1.configure(activebackground="#ececec")
        self.Checkbutton2_1_1_1_1.configure(activeforeground="#000000")
        self.Checkbutton2_1_1_1_1.configure(anchor="w")
        self.Checkbutton2_1_1_1_1.configure(background="#E9EBEE")
        self.Checkbutton2_1_1_1_1.configure(compound="left")
        self.Checkbutton2_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2_1_1_1_1.configure(foreground="#000000")
        self.Checkbutton2_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2_1_1_1_1.configure(highlightcolor="black")
        self.Checkbutton2_1_1_1_1.configure(justify="left")
        self.Checkbutton2_1_1_1_1.configure(text="""Check country""")
        self.Checkbutton2_1_1_1_1.configure(variable=self.checkCheckCountry)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_1_1_1_1_tooltip = ToolTip(self.Checkbutton2_1_1_1_1, self.tooltip_font, """Kiểm tra quốc gia""")

        self.adad_1_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.adad_1_1_1_1_1_1.place(relx=0.012, rely=0.271, relheight=0.048, relwidth=0.172)
        self.adad_1_1_1_1_1_1.configure(activebackground="#ececec")
        self.adad_1_1_1_1_1_1.configure(activeforeground="red")
        self.adad_1_1_1_1_1_1.configure(anchor="w")
        self.adad_1_1_1_1_1_1.configure(background="#E9EBEE")
        self.adad_1_1_1_1_1_1.configure(compound="left")
        self.adad_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.adad_1_1_1_1_1_1.configure(foreground="#000000")
        self.adad_1_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.adad_1_1_1_1_1_1.configure(highlightcolor="black")
        self.adad_1_1_1_1_1_1.configure(justify="left")
        self.adad_1_1_1_1_1_1.configure(text="""Check ch play""")
        self.adad_1_1_1_1_1_1.configure(variable=self.checkCHPlay)
        self.tooltip_font = "TkDefaultFont"
        self.adad_1_1_1_1_1_1_tooltip = ToolTip(self.adad_1_1_1_1_1_1, self.tooltip_font, """Kiểm tra gói mua ch play""")

        self.Checkbutton2_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.Checkbutton2_1_1_1_1_1.place(relx=0.251, rely=0.271, relheight=0.048, relwidth=0.265)
        self.Checkbutton2_1_1_1_1_1.configure(activebackground="#ececec")
        self.Checkbutton2_1_1_1_1_1.configure(activeforeground="#000000")
        self.Checkbutton2_1_1_1_1_1.configure(anchor="w")
        self.Checkbutton2_1_1_1_1_1.configure(background="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1.configure(compound="left")
        self.Checkbutton2_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2_1_1_1_1_1.configure(foreground="#000000")
        self.Checkbutton2_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1.configure(highlightcolor="black")
        self.Checkbutton2_1_1_1_1_1.configure(justify="left")
        self.Checkbutton2_1_1_1_1_1.configure(text="""Check google adsense""")
        self.Checkbutton2_1_1_1_1_1.configure(variable=self.checkGoogleAdsense)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_1_1_1_1_1_tooltip = ToolTip(self.Checkbutton2_1_1_1_1_1, self.tooltip_font, """Kiểm tra tài khoản google adsense""")

        self.adad_1_1_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.adad_1_1_1_1_1_1_1.place(relx=0.012, rely=0.316, relheight=0.048, relwidth=0.184)
        self.adad_1_1_1_1_1_1_1.configure(activebackground="#ececec")
        self.adad_1_1_1_1_1_1_1.configure(activeforeground="red")
        self.adad_1_1_1_1_1_1_1.configure(anchor="w")
        self.adad_1_1_1_1_1_1_1.configure(background="#E9EBEE")
        self.adad_1_1_1_1_1_1_1.configure(compound="left")
        self.adad_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.adad_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.adad_1_1_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.adad_1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.adad_1_1_1_1_1_1_1.configure(justify="left")
        self.adad_1_1_1_1_1_1_1.configure(text="""Check google voice""")
        self.adad_1_1_1_1_1_1_1.configure(variable=self.checkGoogleVoice)
        self.tooltip_font = "TkDefaultFont"
        self.adad_1_1_1_1_1_1_1_tooltip = ToolTip(self.adad_1_1_1_1_1_1_1, self.tooltip_font, """Kiểm tra tài khoản google voice""")

        self.Checkbutton2_1_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.Checkbutton2_1_1_1_1_1_1.place(relx=0.251, rely=0.316, relheight=0.048, relwidth=0.265)
        self.Checkbutton2_1_1_1_1_1_1.configure(activebackground="#ececec")
        self.Checkbutton2_1_1_1_1_1_1.configure(activeforeground="#000000")
        self.Checkbutton2_1_1_1_1_1_1.configure(anchor="w")
        self.Checkbutton2_1_1_1_1_1_1.configure(background="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1_1.configure(compound="left")
        self.Checkbutton2_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2_1_1_1_1_1_1.configure(foreground="#000000")
        self.Checkbutton2_1_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1_1.configure(highlightcolor="black")
        self.Checkbutton2_1_1_1_1_1_1.configure(justify="left")
        self.Checkbutton2_1_1_1_1_1_1.configure(text="""Device logout""")
        self.Checkbutton2_1_1_1_1_1_1.configure(variable=self.checkDeviceLogout)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_1_1_1_1_1_1_tooltip = ToolTip(self.Checkbutton2_1_1_1_1_1_1, self.tooltip_font, """Đăng xuất thiết bị""")

        self.adad_1_1_1_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.adad_1_1_1_1_1_1_1_1.place(relx=0.012, rely=0.361, relheight=0.048, relwidth=0.198)
        self.adad_1_1_1_1_1_1_1_1.configure(activebackground="#ececec")
        self.adad_1_1_1_1_1_1_1_1.configure(activeforeground="red")
        self.adad_1_1_1_1_1_1_1_1.configure(anchor="w")
        self.adad_1_1_1_1_1_1_1_1.configure(background="#E9EBEE")
        self.adad_1_1_1_1_1_1_1_1.configure(compound="left")
        self.adad_1_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.adad_1_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.adad_1_1_1_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.adad_1_1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.adad_1_1_1_1_1_1_1_1.configure(justify="left")
        self.adad_1_1_1_1_1_1_1_1.configure(text="""Check payment methods""")
        self.adad_1_1_1_1_1_1_1_1.configure(variable=self.checkPaymentMethods)
        self.tooltip_font = "TkDefaultFont"
        self.adad_1_1_1_1_1_1_1_1_tooltip = ToolTip(self.adad_1_1_1_1_1_1_1_1, self.tooltip_font, """Kiểm tra phương thức thanh toán""")

        self.Checkbutton2_1_1_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.Checkbutton2_1_1_1_1_1_1_1.place(relx=0.251, rely=0.361, relheight=0.048, relwidth=0.265)
        self.Checkbutton2_1_1_1_1_1_1_1.configure(activebackground="#ececec")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(activeforeground="#000000")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(anchor="w")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(background="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(compound="left")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(justify="left")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(text="""Close payment methods""")
        self.Checkbutton2_1_1_1_1_1_1_1.configure(variable=self.checkClosePaymentMethods)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_1_1_1_1_1_1_1_tooltip = ToolTip(self.Checkbutton2_1_1_1_1_1_1_1, self.tooltip_font, """Đóng phương thức thanh toán""")

        self.adad_1_1_1_1_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.adad_1_1_1_1_1_1_1_1_1.place(relx=0.012, rely=0.406, relheight=0.048, relwidth=0.21)
        self.adad_1_1_1_1_1_1_1_1_1.configure(activebackground="#ececec")
        self.adad_1_1_1_1_1_1_1_1_1.configure(activeforeground="red")
        self.adad_1_1_1_1_1_1_1_1_1.configure(anchor="w")
        self.adad_1_1_1_1_1_1_1_1_1.configure(background="#E9EBEE")
        self.adad_1_1_1_1_1_1_1_1_1.configure(compound="left")
        self.adad_1_1_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.adad_1_1_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.adad_1_1_1_1_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.adad_1_1_1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.adad_1_1_1_1_1_1_1_1_1.configure(justify="left")
        self.adad_1_1_1_1_1_1_1_1_1.configure(text="""Delete payment methods""")
        self.adad_1_1_1_1_1_1_1_1_1.configure(variable=self.checkDeletePaymentMethods)
        self.tooltip_font = "TkDefaultFont"
        self.adad_1_1_1_1_1_1_1_1_1_tooltip = ToolTip(self.adad_1_1_1_1_1_1_1_1_1, self.tooltip_font, """Xóa phương thức thanh toán""")

        self.Checkbutton2_1_1_1_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.Checkbutton2_1_1_1_1_1_1_1_1.place(relx=0.251, rely=0.406, relheight=0.048, relwidth=0.265)
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(activebackground="#ececec")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(activeforeground="#000000")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(anchor="w")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(background="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(compound="left")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(justify="left")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(text="""Create channel youtube""")
        self.Checkbutton2_1_1_1_1_1_1_1_1.configure(variable=self.checkCreateChannelYoutube)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_1_1_1_1_1_1_1_1_tooltip = ToolTip(self.Checkbutton2_1_1_1_1_1_1_1_1, self.tooltip_font, """Tạo kênh youtube""")

        self.Checkbutton2_1_1_1_1_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.place(relx=0.251, rely=0.451, relheight=0.048, relwidth=0.265)
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(activebackground="#ececec")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(activeforeground="#000000")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(anchor="w")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(background="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(compound="left")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(justify="left")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(text="""Confirm security activity""")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1.configure(variable=self.checkConfirmSecurityActivity)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_tooltip = ToolTip(self.Checkbutton2_1_1_1_1_1_1_1_1_1, self.tooltip_font, """Xác nhận cảnh báo đăng nhập""")

        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1 = tk.Checkbutton(self.top)
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.place(relx=0.012, rely=0.451, relheight=0.048, relwidth=0.204)
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(activebackground="#ececec")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(activeforeground="#000000")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(anchor="w")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(background="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(compound="left")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(justify="left")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(text="""Check live die""")
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1.configure(variable=self.checkCheckLiveDie)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton2_1_1_1_1_1_1_1_1_1_1_tooltip = ToolTip(self.Checkbutton2_1_1_1_1_1_1_1_1_1_1, self.tooltip_font, """Kiểm tra mail tồn tại không""")

        self.Checkbutton1_1 = tk.Checkbutton(self.top)
        self.Checkbutton1_1.place(relx=0.468, rely=0.0, relheight=0.048, relwidth=0.168)
        self.Checkbutton1_1.configure(activebackground="#ececec")
        self.Checkbutton1_1.configure(activeforeground="#000000")
        self.Checkbutton1_1.configure(anchor="w")
        self.Checkbutton1_1.configure(background="#E9EBEE")
        self.Checkbutton1_1.configure(compound="left")
        self.Checkbutton1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_1.configure(foreground="#000000")
        self.Checkbutton1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton1_1.configure(highlightcolor="black")
        self.Checkbutton1_1.configure(justify="left")
        self.Checkbutton1_1.configure(text="""Tắt hình ảnh chrome""")
        self.Checkbutton1_1.configure(variable=self.checkTatHinhAnh)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton1_1_tooltip = ToolTip(self.Checkbutton1_1, self.tooltip_font, """Disable Image""")

        self.Checkbutton1_1_1 = tk.Checkbutton(self.top)
        self.Checkbutton1_1_1.place(relx=0.468, rely=0.05, relheight=0.048, relwidth=0.168)
        self.Checkbutton1_1_1.configure(activebackground="#ececec")
        self.Checkbutton1_1_1.configure(activeforeground="#000000")
        self.Checkbutton1_1_1.configure(anchor="w")
        self.Checkbutton1_1_1.configure(background="#E9EBEE")
        self.Checkbutton1_1_1.configure(compound="left")
        self.Checkbutton1_1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_1_1.configure(foreground="#000000")
        self.Checkbutton1_1_1.configure(highlightbackground="#E9EBEE")
        self.Checkbutton1_1_1.configure(highlightcolor="black")
        self.Checkbutton1_1_1.configure(justify="left")
        self.Checkbutton1_1_1.configure(text="""Verify phone""")
        self.Checkbutton1_1_1.configure(variable=self.checkVerifyphone)
        self.tooltip_font = "TkDefaultFont"
        self.Checkbutton1_1_1_tooltip = ToolTip(self.Checkbutton1_1_1, self.tooltip_font, """Verify phone""")

        self.Label1_1_1 = tk.Label(self.top)
        self.Label1_1_1.place(relx=0.686, rely=0.1, height=19, width=115)
        self.Label1_1_1.configure(activebackground="#f9f9f9")
        self.Label1_1_1.configure(activeforeground="black")
        self.Label1_1_1.configure(anchor="w")
        self.Label1_1_1.configure(background="#E9EBEE")
        self.Label1_1_1.configure(compound="left")
        self.Label1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1_1.configure(foreground="#000000")
        self.Label1_1_1.configure(highlightbackground="#E9EBEE")
        self.Label1_1_1.configure(highlightcolor="black")
        self.Label1_1_1.configure(text="""Change proxy after""")
        self.tooltip_font = "TkDefaultFont"
        self.Label1_1_1_tooltip = ToolTip(self.Label1_1_1, self.tooltip_font, """Thay proxy sau""")

        self.Label1_1_1_1 = tk.Label(self.top)
        self.Label1_1_1_1.place(relx=0.927, rely=0.1, height=19, width=44)
        self.Label1_1_1_1.configure(activebackground="#f9f9f9")
        self.Label1_1_1_1.configure(activeforeground="black")
        self.Label1_1_1_1.configure(anchor="w")
        self.Label1_1_1_1.configure(background="#E9EBEE")
        self.Label1_1_1_1.configure(compound="left")
        self.Label1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1_1_1.configure(foreground="#000000")
        self.Label1_1_1_1.configure(highlightbackground="#E9EBEE")
        self.Label1_1_1_1.configure(highlightcolor="black")
        self.Label1_1_1_1.configure(text="""turn""")
        self.tooltip_font = "TkDefaultFont"
        self.Label1_1_1_1_tooltip = ToolTip(self.Label1_1_1_1, self.tooltip_font, """lượt""")

        self.spinChangeProxy = ttk.Spinbox(self.top, from_=1, to=100)
        self.spinChangeProxy.place(relx=0.83, rely=0.1, relheight=0.048, relwidth=0.084)
        self.spinChangeProxy.configure(background="white")
        self.spinChangeProxy.configure(takefocus="")


# Support code for Balloon Help (also called tooltips).
# derived from http://code.activestate.com/recipes/576688-tooltip-for-tkinter/
from time import time, localtime, strftime


class ToolTip(tk.Toplevel):
    """Provides a ToolTip widget for Tkinter."""

    def __init__(self, wdgt, tooltip_font, msg=None, msgFunc=None, delay=0.5, follow=True):
        self.wdgt = wdgt
        self.parent = self.wdgt.master
        tk.Toplevel.__init__(self, self.parent, bg="black", padx=1, pady=1)
        self.withdraw()
        self.overrideredirect(True)
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set("No message provided")
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        tk.Message(self, textvariable=self.msgVar, bg="#FFFFDD", font=tooltip_font, aspect=1000).grid()
        self.wdgt.bind("<Enter>", self.spawn, "+")
        self.wdgt.bind("<Leave>", self.hide, "+")
        self.wdgt.bind("<Motion>", self.move, "+")

    def spawn(self, event=None):
        self.visible = 1
        self.after(int(self.delay * 1000), self.show)

    def show(self):
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()

    def move(self, event):
        self.lastMotion = time()
        if self.follow is False:
            self.withdraw()
            self.visible = 1
        self.geometry("+%i+%i" % (event.x_root + 20, event.y_root - 10))
        try:
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)

    def hide(self, event=None):
        self.visible = 0
        self.withdraw()

    def update(self, msg):
        self.msgVar.set(msg)


#                   End of Class ToolTip


def start_up():
    gui_support.main()


if __name__ == "__main__":
    gui_support.main()
